#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

# General information about the project.
project = 'Journal de Manip'
copyright = '2017, Poltergeist42'
author = 'Poltergeist42'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '20170523'
# The full version, including alpha/beta/rc tags.
release = '20170523'

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [  'sphinx.ext.autodoc'
                ,'sphinx.ext.githubpages'
                ,'sphinx.ext.todo'
                ,'sphinx.ext.mathjax'
                ,"sphinx.ext.viewcode"
                ,'sphinx.ext.graphviz'
                ,'sphinxcontrib.plantuml'
                ,'sphinx.ext.todo'
                ,'sphinx_ahd_theme'
             ]

plantuml = 'java -jar /usr/share/plantuml/plantuml.jar'

plantuml_output_format = 'svg_img'
graphviz_output_format = "svg"

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

html_title = project

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
## Theme : alabaster
#html_theme = 'alabaster'

## Theme : classic
# html_theme = 'classic'

## Theme Jypyter
# import jupyter_sphinx_theme
# html_theme = "jupyter"
# html_sidebars = {'**': ['sidebartoc.html']}
# html_theme_path = jupyter_sphinx_theme.get_html_theme_path()

## Theme : Karma
# pip install karma_sphinx_theme
# html_theme = "karma_sphinx_theme"

# html_theme = 'sphinx_pdj_theme'
# html_theme_path = [sphinx_pdj_theme.get_html_theme_path()]

## Theme : sphinx-ahd-theme
# Doc : https://sphinx.ahd-creative.agency/
# pip install sphinx-ahd-theme
# extensions = ['sphinx_ahd_theme', ...]
html_theme = 'sphinx_ahd_theme'


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    #'stickysidebar ': True, # pas supportee par nature
    'externalrefs' : 'false',
    'highlighttoc' : 'true',
    'lighter_header_decor' : 'false',
    'borderless_decor' : 'false',
    'default_layout_text_size' : '100%',
    'sidebar_master_title' : 'master title',
    'sidebar_root_title' : 'root_titer',
    'sidebar_prev_title' : 'Page précédente',
    'sidebar_next_title' : 'Page suivante',
    'max_width' : '80%'
}

# These are options specifically for the Wagtail Theme.
html_theme_options = dict(
    project_name = project
    ,logo = "img/ColorLogoOpenHardware-noBackground.svg"
    ,logo_alt = "logoGrenouilleTech"
    # ,logo_height = 59
    ,logo_height = 400
    # ,logo_url = "/"
    # ,logo_width = 45
    ,logo_width = 500
)

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['_static']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'JDMdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'JDM.tex', 'JDM Documentation',
     'Poltergeist42', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'jdm', 'JDM Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'JDM', 'JDM Documentation',
     author, 'JDM', 'One line description of project.',
     'Miscellaneous'),
]

